server:
  port: 1010

spring:
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      host: "localhost"
      port: 6379
      username: web-messenger
      password: Messenger@123
    mongodb:
      host: "localhost"
      port: 27017
      username: web-messenger
      password: Messenger@123
      database: messenger
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/messenger
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: "webMessenger"